language: C

sudo: required
dist: trusty

compiler:
  - gcc
# Nope, travis can't do clang because it seems to want to compile libcroc with clang
# and that doesn't work. Why it feels compelled to do this I don't know. And why
# libcroc can't be compiled with clang is also weird.
#  - clang

group: edge

before_script:
  - sudo apt-get update
  - sudo apt-get install -y automake autopoint gettext libreadline-dev wget texinfo
  - wget ftp://ftp.gnu.org/pub/gnu/gettext/gettext-0.19.8.tar.xz
  - tar -xpf gettext-0.19.8.tar.xz
  - (cd ./gettext-0.19.8 && CC=gcc ./configure --prefix=/usr && make && sudo make install)
  - rm -fr gettext-0.19.8
  - bash -x ./autogen.sh

# Configure and run the tests
script:
 - make && TRAVIS=1 make check
