language: C

sudo: required
dist: trusty

group: edge

before_script:
  sudo apt-get install -y automake-1.15 autopoint gettext libreadline-dev wget texinfo

# Configure and run the tests
script:
 - (cd doc && make stamp-vti) && make && TRAVIS=1 make check
